### ISSUE TITLE
Next steps?

### ISSUE THREAD

**Issue by kodonnell** [swils/vscode-markdown-scripture#10]
Hi @swils,

Great work - this looks really useful! I'm interested to know what you have planned next, and if I can help out. I've been thinking about this a bit, and what I'd want from a bible note taking system and:

- I think something like foam (https://github.com/foambubble/foam) or makrdown-notes (https://github.com/kortina/vscode-markdown-notes) has a lot of functionality (especially backlinks etc. which I think will be really nice e.g. "show me all my notes where I've referenced John 3:16" etc.). No sense reinventing the wheel, so something that integrates nicely with these would be great.
- Unfortunately, it doesn't seem to support the nested/range structure of verse links (e.g. `john#3:16-18`). The best you could do would be to create a file per verse and something like `john/3/16` or maybe per chapter with `john/3#16`. Which isn't terrible TBH, and then you get nice code completion etc. - it just makes reading your source bible harder. I don't see how it'd support `john/3#16-18` though - we'd need something specific for that.
- Furthermore, while I like how your extension works, I'd actually want the raw scripture inserted into the markdown, not just into the render. This is because a) it keeps raw markdown powering things (as opposed to relying on this extension/vscode being maintained etc.), and b) it means I can edit the scripture (emphasis, add notes, etc.). NB: A potential downside is that updating references would need a bit of thinking (e.g. if the user has edited an inserted block, and then wants it updated), but that seems doable. This is how https://github.com/kuchejak/obsidian-bible-linker-plugin does it. (The hidden verse references are clever for backlinks to each individual verse.) 

Some thoughts:

- VS Code have just started using a markdown language server. They require you to provide your own `markdown-it` parser, which you've done. This presumably then gives a lot of things for free (definitions etc.?). I'm not familiar with language servers, but it's possibly a way forward and will eventually mean nice support for e.g. "Go to definition" etc.
- I really like the [create note from selection feature](https://github.com/kortina/vscode-markdown-notes#new-note-from-selection-command) and it could be very useful i.e. navigate to your chapter (possibly in a nice preview window with a search bar?), and while reading select the text you want and "Copy scripture reference" which you can then paste elsewhere.
- I'd personally accept the superscript 'extension' to Markdown for verse numbers - I find it's just a lot nicer to read. (Already supported in vscode with `<sup>1</sup>` but not `^1^`.)
- I can't decide on extending [[wikilinks]] and then trying to force other tools to work with it (e.g. verses + ranges). I see three options:
  1. Hack away at existing [[wikilink]] providers to add support for verse ranges etc., and backlinks to sections not files. Potentially a lot of development work maintaining the fork, etc.
  1. Keep [[wikilinks]] but take the approach of https://github.com/kuchejak/obsidian-bible-linker-plugin i.e. a custom command for inserting links to verses. This maintains all the power of backlinks etc., without much effort for the user. But ... I feel like changing/updating links could get messy, and those hidden links are a bit superfluous and might make reading really hard if you use word wrap.
  1. Don't use [[wikilinks]] for bible references (though users may still use it for their notes etc.). Treat the bible linking separately - which is what you're doing by using single square brackets. Anyway, then you could easily have the bible in chapters, or even a single markdown file. Then we roll the linking like you've done (potentially with full inserts of text), and roll our own backlinking (which should be easy to do if it's purely for finding all references to a given bit of scripture.) This does mean you lose the full power of backlinks (e.g. the network graph of foam), but it's also much cleaner to keep it separate from the [[wikilink]] style tools.
 
There's a lot there, but I'm keen on your thoughts given you've been actively using this, and presumably have researched a lot of other tools.

**Comment by swils** [comment]
First of all: I’ve just released a new version 0.2.0 of the extension. This version allows you to leverage all of CSS to implement superscripts for verse numbers. I’ve started to render verse numbers with superscripts myself now :-) Look at the docs.

For the coming weeks/month(s) my main focus remains on integrating Sword: this gives access to a massive collection of Bible translations with annotations.

I will get back to you later on the other things! You've given me a lot of food for thought, but I have to chew on it for a while. (First I'd have to look at the Markdown language server/service and the plugin you mentioned... it's good you mentioned these now, they may yet change the way I do the Sword integration.)

**Comment by kodonnell** [comment]
Good work on superscripts!

Sword seems good, apart from [this bit](https://wiki.crosswire.org/EnduserFAQ#Do_you_or_will_you_have_NIV.2FNASB.2FNLT.2FMessage.2FNKJV.2FNRSV.2Fetc..3F)

>  Most publishers of the most popular modern English translations have not been interested in publishing their material in our format ...

Even the ESV (which they say is an exception) currently can't be downloaded (though that might be a hosting issue - link [here](http://www.crosswire.org/sword/modules/ModInfo.jsp?modName=ESV)). So ... maybe a lot of work that won't provide the translations a significant part of the audience use?

Re your plans/timelines - no worries. I have some free time, so may look at implementing some of my ideas separately. For example, I realised the other day that snippets will basically work out-of-box. However, I may go the language server route too, as that's likely to give me other freebies in future if I want, and I get to learn more. If I end up doing it and it's useful, I'll post it here.

Closing this for now.

**Comment by kodonnell** [comment]
Just to close this out - I've settled on something that's worked for me. I've used it for long and short studies so far, and I'm really enjoying this + VSCode + Markdown instead of Word etc.

![image](https://user-images.githubusercontent.com/8204904/206843373-da2a7b66-bcea-42d0-8f70-db66a92f3842.png)


Summarising decisions/findings/features if it's useful here:

- I gave up on [[wikilinks]] integration. I think the only way to really make it work well is a bespoke tweak of foam (or similar [[wikilinks]] providers) to support verses and ranges etc. (not just "refer a heading from this other document"). And for the bit of functionality I wanted (finding e.g. everywhere I reference a particular verse) that's very easy to script up. So for now, I use [[wikilinks]], but not with bible verses.
- I just use normal markdown links/references as footnotes. That way while you're writing the text a reference isn't too distracting, but it's all there at the end. (And VSCode links you to it in preview etc.) And I can edit the text if I want e.g. add emphasis etc.
- Decided on `<sup></sup>` for verse numbers as I reckon that looks best and is sorta still markdown. (I could use `^^` but it's not standard Markdown.) I like the bold references too.
- From above you can see I've got various decoration. I've also got diagnostics for various things, and previews so when you hover over a reference you see the text. And different translation support (though I settled on the WEB as it's free/open and I like it).
- I use a command that opens up a quickInput to insert things in various forms e.g. you type out "John 3:16-18" and (after it validates) choose if you want a reference with/without text, or a block quote etc. It does all the formatting/linking etc. I did try out auto-complete and had that working, but ... I actually can't remember the reason it didn't work well! I think it might have been that since I'm now appending footnotes at the end of a doc as well as the current selection, it didn't really make sense for autocompletion, even though it was a nicer experience. (Could do the same with an input, but I'm lazy and the quick input gets most of the way there. I autocomplete the book first which is most of the typing/spelling anyway.)
- Oh I also tried a language server, and while it worked, it didn't really make sense for the same reasons above. I guess I could switch to using it for diagnostics/decorations.

Anyway, I guess the main difference with your approach was sticking to standard markdown. I largely went this way as then the actual verses are in the markdown (which also means I can emphasise etc.) and it'll render in any renderer. Aside from that, I think they're largely similar, and I have similar todos as you e.g. partial references (or across chapter), book names, etc.

NB: I know you're looking at using Sword - to get the WEB translation, I used pysword and just converted it straight to JSON with the attributes I care about.
